### PR TITLE
fix(src): don't persist Redis state for tokens with failed price calc

### LINKED ISSUE #306: addNewTokenToCache persists Redis state for tokens whose price calculation fails
## Summary

`PriceClient.addNewTokenToCache` creates a RedisTimeSeries key and increments a member of the `token_counter` sorted set **before** attempting to calculate the token's price. When the price calculation throws (e.g. `PathsNotFoundError` for a token with no Stellar paths to USDC), the outer catch swallows the error and returns `null`, but the TimeSeries key and sorted-set entry have already been committed and are never cleaned up.

The price-update worker then reads every member of `token_counter` on each tick (`getTokensToUpdate` does `zRange(KEY, 0, -1)`), so these orphan entries are retried indefinitely on every cycle, each time failing the same way.

## Where it happens

`src/service/prices/index.ts:582-615` — `addNewTokenToCache`:

```ts
private addNewTokenToCache = async (token) => {
  ...
  tsKey = this.getTimeSeriesKey(token);
  await this.createTimeSeries(tsKey);                 // ts.create + zIncrBy run unconditionally
  const { timestamp, price } = await this.calculatePriceInUSD(token);  // throws for unresolvable tokens
  ...
};
```

`src/service/prices/index.ts:548-571` — `createTimeSeries` writes both the TS key and the sorted-set member:

```ts
await this.redisClient.ts.create(key, { RETENTION: PriceClient.RETENTION_PERIOD, ... });
await this.redisClient.zIncrBy(PriceClient.TOKEN_COUNTER_SORTED_SET_KEY, 1, key);
```

`RETENTION` applies to *samples* inside a TimeSeries key, not to the key itself, so a TS that never receives a sample is never trimmed. The sorted set has no TTL and `addBatchToCache` (`src/service/prices/index.ts:414-429`) filters out failed batch members but does not `zRem` them, so failures accumulate across worker cycles too.

## Steps to reproduce

1. Submit a token to `POST /api/v1/token-prices` whose code is alphanumeric and whose issuer is a syntactically valid Ed25519 public key but for which no Stellar path to USDC exists (e.g. a freshly-generated keypair).
2. Observe that `priceClient.getPrice(token)` returns `null` (expected).
3. Inspect Redis:
   - `ZSCORE freighter:tokenCounterSortedSet ts:price:<token>` → returns `1` (unexpected — the price calculation failed).
   - `TS.INFO ts:price:<token>` → key exists with zero samples (unexpected).
4. The next worker tick will list this entry via `getTokensToUpdate`, run two Horizon calls (`ledgers().order().limit(1)` and `strictReceivePaths`) against it, fail the same way, and leave the entry in place. This repeats on every subsequent tick.

## Suggested fix

Two complementary changes:

1. **Persist only on success.** Reorder `addNewTokenToCache` so `calculatePriceInUSD` runs before `createTimeSeries`. If price calculation throws, the TS key and sorted-set member are never written.

   ```ts
   private addNewTokenToCache = async (token) => {
     if (!this.redisClient) throw new Error("Redis client not initialized");
     let result: PriceCalculationResult;
     try {
       result = await this.calculatePriceInUSD(token);
     } catch (e) {
       this.logger.error(ensureError(e, `calculating price for ${token}`));
       return null;
     }
     const tsKey = this.getTimeSeriesKey(token);
     await this.createTimeSeries(tsKey);
     await this.redisClient.ts.add(tsKey, result.timestamp, result.price.toNumber());
     return { currentPrice: result.price, percentagePriceChange24h: null };
   };
   ```

2. **Evict failed entries in the worker.** In `addBatchToCache`, track tokens whose `calculatePriceInUSD` rejected and `zRem` them from `token_counter` (and `ts.del` the empty TS key). This prevents pre-existing orphan entries from being retried forever after deploying fix #1, and acts as defense-in-depth against future regressions.

## Verification

Add a unit test in `src/service/prices/index.test.ts` covering: mock `calculatePriceInUSD` to reject with `PathsNotFoundError`; call `getPrice('FAKE:G...')`; assert that `redisClient.ts.create` was not called and that `zIncrBy` against `token_counter` was not called.

### PR DESCRIPTION
**Pull request by aristidesstaffieri**
Closes #306 

`addNewTokenToCache` used to create the TS key and zIncrBy token_counterbefore calculating the price. When calculatePriceInUSD threw (e.g. PathsNotFoundError for tokens with no Stellar path to USDC), the outer catch returned null but left an orphan TS key and sorted-set entry, which the worker then retried forever on every tick.

- Reorder `addNewTokenToCache` so `calculatePriceInUSD` runs first; only create the TS key and increment `token_counter` on success.
- Defense-in-depth: in `addBatchToCache`, evict tokens whose calc failed AND whose TS has zero samples (zRem + del). Healthy tokens with existing samples are left alone for retry.

### CODE REVIEW

File: src/service/prices/index.ts [hunk 1]
```diff
@@ -428,6 +439,38 @@ export class PriceClient {
...
+      let hasSamples = false;
+      try {
+        const latest = await this.redisClient.ts.get(tsKey);
+        hasSamples = !!latest;
+      } catch (e) {
+        // Key does not exist — still want to drop the sorted-set entry.
+        hasSamples = false;
+      }
+
+      if (hasSamples) {
```
[the remark this answers is not in the document]
Comment (aristidesstaffieri) [reply src/service/prices/index.ts:459]: fixed in e8e209789d6132297a058475fd16e1e3893d7b40

File: src/service/prices/index.ts [hunk 2]
```diff
@@ -582,36 +625,39 @@ export class PriceClient {
...
+      this.logger.error(ensureError(e, `calculating price for ${token}`));
+      return null;
+    }
 
-      return {
-        currentPrice: price,
-        percentagePriceChange24h: null,
-      } as TokenPriceData;
+    const tsKey = this.getTimeSeriesKey(token);
+    try {
```
[the remark this answers is not in the document]
Comment (aristidesstaffieri) [reply src/service/prices/index.ts:648]: fixed in e8e209789d6132297a058475fd16e1e3893d7b40

File: src/service/prices/index.test.ts [hunk 3]
```diff
@@ -284,6 +284,31 @@ describe("Token Price Client", () => {
...
+      expect(result).toBeNull();
+      // No orphan TS key
+      expect(mockRedisClient.ts.create).not.toHaveBeenCalled();
+      expect(mockRedisClient.ts.add).not.toHaveBeenCalled();
+      // No orphan sorted-set entry
+      expect(mockRedisClient.zIncrBy).not.toHaveBeenCalledWith(
+        "token_counter",
+        expect.anything(),
+        expect.stringContaining("FAKE:"),
+      );
```
[the remark this answers is not in the document]
Comment (aristidesstaffieri) [reply src/service/prices/index.test.ts]: fixed in e8e209789d6132297a058475fd16e1e3893d7b40

File: src/service/prices/index.ts [hunk 4]
```diff
@@ -428,6 +439,59 @@ export class PriceClient {
...
+      const tsKey = this.getTimeSeriesKey(token);
+      let shouldEvict = false;
+      try {
+        const latest = await this.redisClient.ts.get(tsKey);
+        shouldEvict = !latest;
+      } catch (e) {
+        // ts.get failed — only treat as orphan if the key truly does not
+        // exist. A transient Redis error must not evict a healthy token.
+        try {
+          const exists = await this.redisClient.exists(tsKey);
```
Comment (JakeUrban) [inline src/service/prices/index.ts]: Do we really need to defend against transient redis errors? If so, shouldn't we have a retry mechanism we can apply to all requests made by the client? If this was AI being overly cautious, lets remove the inner try/catch.

**Review by JakeUrban — APPROVED** [review]

File: src/service/prices/index.ts (hunk 4 above)
Comment (aristidesstaffieri) [reply src/service/prices/index.ts]: yeah this is very edge case and there isn't a retry mechanism at the  redis client level today. I reverted the inner block in 4b5a33d4eb98c2ec6f4f5494f90a1ed024ebfbe6

File: src/service/prices/index.ts [hunk 5]
```diff
@@ -582,36 +627,42 @@ export class PriceClient {
...
+      this.logger.error(ensureError(e, `calculating price for ${token}`));
+      return null;
+    }
 
-      return {
-        currentPrice: price,
-        percentagePriceChange24h: null,
-      } as TokenPriceData;
+    try {
+      await this.createTimeSeries(tsKey);
```
Comment (piyalbasu) [inline src/service/prices/index.ts:649]: NIT: but if this.redisClient.ts.add fails, the time series will still be created. I believe this would be cleaned up by `evictOrphans`, but not until this job runs

Comment (aristidesstaffieri) [reply src/service/prices/index.ts:649]: yeah so this was intentional because the eviction path already covers this but I see that we can compensate for this further by eliminating the orphan window in the catch arm. Added in 97209aeecb4499eb7361d5af403085d69cf0fbf2

**Review by piyalbasu — APPROVED** [review]
